"""Produce the demonstration in /evidence.

Runs the replay scenarios end to end against the mock console and writes each
one to its own directory, so the evidence is reproducible rather than a set of
logs somebody once pasted in.

The two discovery runs are not re-run here: they cost money and involve a
model, so what is committed is the evidence from the runs that actually
happened. Everything downstream of them is regenerated by this script.

    python scripts/capture_evidence.py

The scenarios are chosen to walk the whole result contract, and one pair of
them makes a point that is easy to miss: the same unknown member ID produces
a loud failure against the freshly discovered draft and a clean business
outcome against the reviewed capability. Nothing about the automation changed
between those two runs. What changed is that a person declared what the
application's answer means.
"""

from __future__ import annotations

import shutil
import socket
import sys
import threading
from pathlib import Path

import uvicorn
from dotenv import load_dotenv

from cua.artifact import load, load_latest
from cua.escalation import Handback, SessionControl
from cua.evidence import Recorder
from cua.replay import ReplayEngine
from cua.safety import Policy
from cua.surfaces.web import WebSurface

BASE_PORT = 8099
EVIDENCE = Path("evidence/runs")
CREDENTIALS = {"operator_id": "teller01", "operator_password": "Passw0rd!"}
SECRETS = set(CREDENTIALS.values())


def serve_mock() -> None:
    """Serve the console on the port the capabilities were recorded against."""
    with socket.socket() as probe:
        if probe.connect_ex(("127.0.0.1", BASE_PORT)) == 0:
            print(f"using the console already serving on :{BASE_PORT}")
            return
    from mockbank.app import app

    server = uvicorn.Server(uvicorn.Config(app, host="127.0.0.1", port=BASE_PORT, log_level="error"))
    threading.Thread(target=server.run, daemon=True).start()
    for _ in range(200):
        if server.started:
            return
        threading.Event().wait(0.05)
    raise SystemExit("the mock console did not start")


def arm(kind: str, count: int = 1) -> None:
    import json
    import urllib.request

    urllib.request.urlopen(urllib.request.Request(
        f"http://127.0.0.1:{BASE_PORT}/_test/fault",
        data=json.dumps({"kind": kind, "count": count}).encode(),
        headers={"content-type": "application/json"}))


def run(label: str, capability, inputs, *, policy=None, escalator=None,
        authorise=False, fault=None, note=""):
    directory = EVIDENCE / label
    if directory.exists():
        shutil.rmtree(directory)
    if fault:
        arm(fault)

    control = SessionControl()
    recorder = Recorder(label, EVIDENCE, secrets=SECRETS)
    surface = WebSurface()
    try:
        engine = ReplayEngine(
            surface, recorder,
            policy or Policy.load("policy.yaml"),
            escalator=escalator, control=control, step_timeout_ms=8_000)
        result = engine.run(capability, inputs, authorise_irreversible=authorise)
    finally:
        surface.close()

    (directory / "scenario.txt").write_text(
        f"{label}\n\n{note}\n\ncapability: {capability.id} v{capability.version} "
        f"({capability.approval})\nresult: {result.status.value}\n{result.describe()}\n")
    print(f"  {label:42} {result.status.value:17} {result.describe()[:60]}")
    return result


def main() -> int:
    load_dotenv()
    serve_mock()
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    balance_draft = load(Path("capabilities/member_savings_balance.v1.json"))
    balance = load_latest("member_savings_balance")
    subaccount = load_latest("open_member_subaccount")
    creds = dict(CREDENTIALS)

    print("\nreplaying the discovered capabilities:\n")

    run("03-replay-success", balance, {"member_id": "100234", **creds},
        note="The capability recorded by the discovery run, replayed with no model in the "
             "decision loop. Returns the outputs it declares.")

    run("04-replay-member-never-recorded", balance, {"member_id": "100781", **creds},
        note="The same capability, invoked for a member the discovery run never saw. This is "
             "what parameterising the recording buys: the artifact describes the screen, not "
             "the one visit to it that produced it.")

    run("05-replay-draft-unknown-member", balance_draft, {"member_id": "999999", **creds},
        note="An unknown member, against the capability exactly as discovery produced it. The "
             "draft has no business outcomes declared -- a run that succeeds cannot observe "
             "what happens when things go otherwise -- so the flow fails, loudly and with a "
             "precise diagnosis, rather than quietly returning nothing. Compare with 06.")

    run("06-replay-reviewed-unknown-member", balance, {"member_id": "999999", **creds},
        note="The same unknown member against the reviewed capability. Nothing about the "
             "automation changed between this run and 05. What changed is that a person "
             "declared what the console's answer means, so 'no such member' is now reported "
             "as a business outcome the caller can act on rather than as a failure.")

    run("07-replay-recovers-from-interstitial", balance, {"member_id": "100234", **creds},
        fault="interstitial",
        note="The console interposes a maintenance notice mid-flow. Replay recognises a "
             "declared, bounded recovery, clears it, and completes. The recovery is recorded "
             "on the result rather than becoming it.")

    run("08-replay-application-error", balance, {"member_id": "100234", **creds},
        fault="app_error",
        note="The console falls over. Reported immediately as an application error rather "
             "than waited out and reported as a timeout, because the capability declares what "
             "its error page looks like. The distinction matters: this failure is not the "
             "automation's fault, and the report says so.")

    run("09-replay-session-expiry", balance, {"member_id": "100234", **creds},
        fault="session_timeout",
        note="The session expires mid-flow. This capability only reads, so re-authenticating "
             "and replaying from the start changes nothing -- which is what makes the recovery "
             "safe here and would not make it safe in a flow that writes.")

    print("\nhanding a stuck run to a person:\n")

    # A separate, committed policy that permits irreversible actions, so the
    # remaining gate is the one only a person can pass.
    with_irreversible = Policy.load("policy.escalation-demo.yaml")

    class Operator:
        """Stands in for a person at the session. A production console would
        present this; the decision and the control transfer are the same."""

        def escalate(self, intervention):
            print(f"    intervention {intervention.request_id}: {intervention.failure_kind} "
                  f"at step {intervention.step_index} ({intervention.step_intent})")
            print(f"    live session: {(intervention.live_session_url or '-')[:64]}...")
            return Handback(
                disposition="resume", operator="j.okafor",
                note="Reviewed the request against the member's file; the deposit is within "
                     "policy and the product is available. Authorising the submission.",
                authorise_irreversible=True)

    run("10-escalation-irreversible-authorised", subaccount,
        {"member_id": "100234", "product": "Vacation Club", "opening_deposit": "150.00",
         "nickname": "Summer Trip", **creds},
        policy=with_irreversible, escalator=Operator(),
        note="A write flow stops at its irreversible step because the caller did not "
             "authorise one. An intervention request is raised carrying a link into the "
             "session the automation was already using -- not a fresh one -- and the "
             "automation is structurally unable to act while the operator holds it. The "
             "operator authorises that single submission, hands back, and the run completes.")

    run("11-replay-restricted-member", subaccount,
        {"member_id": "100999", "product": "Regular Savings", "opening_deposit": "100.00",
         "nickname": "Rainy Day", **creds},
        policy=with_irreversible, authorise=True,
        note="A permission denial. The institution has already made this decision, so there "
             "is nothing for an operator to resolve and nobody is called: it is reported to "
             "the caller as a business outcome.")

    print(f"\nwritten to {EVIDENCE}/\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
